'use client';

import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, Check, ChevronRight, Clock3, ImageIcon, ImagePlus, Mic, Pause, Play, RotateCcw, Shuffle, Sparkles, Trophy, Upload, Users, Volume2 } from 'lucide-react';
import topics from './data/speaking-topics.json';
import roleTopics from './data/roleplay-topics.json';

type Screen = 'dashboard' | 'setup' | 'prep' | 'speak' | 'done' | 'sample' | 'roleplay';
const PREP_SECONDS = 20;
const SPEAK_SECONDS = 90;

function RolePlay({ back }: { back: () => void }) {
  const [topic, setTopic] = useState(roleTopics[0]);
  const [phase, setPhase] = useState<'choose' | 'prep' | 'talk' | 'done'>('choose');
  const [left, setLeft] = useState(PREP_SECONDS);
  const [paused, setPaused] = useState(false);
  useEffect(() => {
    if (phase === 'choose' || phase === 'done' || (phase === 'talk' && paused)) return;
    if (left <= 0) { if (phase === 'prep') { setPhase('talk'); setLeft(300); } else setPhase('done'); return; }
    const id = setTimeout(() => setLeft(value => value - 1), 1000);
    return () => clearTimeout(id);
  }, [phase, left, paused]);
  const choose = (item: typeof roleTopics[number]) => { setTopic(item); setLeft(PREP_SECONDS); };
  const start = () => { setLeft(PREP_SECONDS); setPaused(false); setPhase('prep'); };
  if (phase === 'choose') return <section className="page roleplay"><button className="back" onClick={back}><ArrowLeft size={17}/> ALL MODULES</button><div className="heading"><span className="eyebrow purple"><Users size={15}/> FUNGLISH · ROLE PLAY</span><h2>Choose a conversation</h2><p>Pick a real-life situation together, then prepare for 20 seconds and talk for 5 minutes.</p></div><div className="role-layout"><div className="topic-list role-list"><div className="library-title"><h3>Role play bank</h3><button className="random" onClick={() => choose(roleTopics[Math.floor(Math.random() * roleTopics.length)])}><Shuffle size={16}/> Random topic</button></div>{roleTopics.map(item => <button className={`topic-row ${topic.id === item.id ? 'chosen' : ''}`} onClick={() => choose(item)} key={item.id}><span>{item.title}</span>{topic.id === item.id && <Check size={17}/>}</button>)}</div><RoleCards topic={topic} preview/><div className="role-start"><Button onClick={start}>Start role play <ArrowRight size={19}/></Button></div></div></section>;
  if (phase === 'done') return <section className="page done"><div className="trophy"><Trophy size={52}/></div><h2>Great conversation!</h2><p>You completed a five-minute role play.</p><div className="topic-done"><strong>{topic.title}</strong><p>{topic.challenge}</p></div><div className="actions"><Button onClick={() => setPhase('choose')}>Choose another topic</Button><Button kind="secondary" onClick={back}>Back to modules</Button></div></section>;
  const preparing = phase === 'prep';
  return <section className="page stage role-stage"><div className="stage-top"><div><span className="eyebrow purple"><Users size={15}/> {preparing ? 'PREPARATION TIME' : 'ROLE PLAY IN PROGRESS'}</span><h2>{preparing ? 'Get into character!' : 'Talk it out!'}</h2><p>{preparing ? 'Read your role and think of helpful language.' : 'Work together to complete the challenge.'}</p></div><Timer remaining={left} total={preparing ? PREP_SECONDS : 300} label={preparing ? 'PREP' : 'LEFT'} danger={!preparing}/></div><RoleCards topic={topic}/><div className="actions">{preparing ? <><Button kind="secondary" onClick={() => setPhase('choose')}><ArrowLeft size={18}/> Change topic</Button><Button onClick={() => { setLeft(300); setPhase('talk'); }}>Start talking <ArrowRight size={18}/></Button></> : <><Button kind="secondary" onClick={() => setPaused(value => !value)}>{paused ? <Play size={18}/> : <Pause size={18}/>} {paused ? 'Resume' : 'Pause'}</Button><Button kind="danger" onClick={() => setPhase('done')}><Check size={18}/> Finish early</Button></>}</div></section>;
}

function RoleCards({ topic, preview = false }: { topic: typeof roleTopics[number]; preview?: boolean }) { return <div className={`role-cards ${preview ? 'role-preview' : ''}`}><div className="role-title"><span className="eyebrow purple">ROLE PLAY</span><h3>{topic.title}</h3></div><div className="players"><article className="player player-a"><span>STUDENT A · {topic.aRole}</span><p>{topic.aText}</p><strong>YOUR GOAL</strong><b>{topic.aGoal}</b></article><article className="player player-b"><span>STUDENT B · {topic.bRole}</span><p>{topic.bText}</p><strong>YOUR GOAL</strong><b>{topic.bGoal}</b></article></div><div className="challenge"><Trophy size={18}/><div><strong>CHALLENGE</strong><p>{topic.challenge}</p></div></div></div>; }

function SpeakingSample({ back }: { back: () => void }) {
  const [topic, setTopic] = useState(topics[0]), [phase, setPhase] = useState<'choose'|'prep'|'speak'|'done'>('choose'), [left, setLeft] = useState(30), [paused, setPaused] = useState(false);
  useEffect(() => { if (phase !== 'prep' && (phase !== 'speak' || paused)) return; if (left <= 0) { if (phase === 'prep') { setPhase('speak'); setLeft(180); } else setPhase('done'); return; } const id = setTimeout(() => setLeft(v => v - 1), 1000); return () => clearTimeout(id); }, [phase, left, paused]);
  const random = () => setTopic(topics[Math.floor(Math.random() * topics.length)]);
  if (phase === 'choose') return <section className="page sample"><button className="back" onClick={back}><ArrowLeft size={17}/> ALL MODULES</button><div className="heading"><span className="eyebrow"><Mic size={15}/> SPEAKING SAMPLE</span><h2>Choose a topic</h2><p>You’ll have 30 seconds to prepare, then 3 minutes to speak.</p></div><div className="sample-layout"><div className="topic-list"><div className="library-title"><h3>Topic bank</h3><button className="random" onClick={random}><Shuffle size={16}/> Random topic</button></div>{topics.map(item => <button className={`topic-row ${topic.id === item.id ? 'chosen':''}`} onClick={() => setTopic(item)} key={item.id}><span>{item.title}</span>{topic.id === item.id && <Check size={17}/>}</button>)}</div><div className="topic-preview"><span className="eyebrow">YOUR TOPIC</span><h3>{topic.title}</h3><p>{topic.prompt}</p><Button onClick={() => { setLeft(30); setPhase('prep'); }}>Start practice <ArrowRight size={19}/></Button></div></div></section>;
  if (phase === 'done') return <section className="page done"><div className="trophy"><Trophy size={52}/></div><h2>Great speaking!</h2><p>You completed a three-minute speaking sample.</p><div className="topic-done"><strong>{topic.title}</strong><p>{topic.prompt}</p></div><div className="actions"><Button onClick={() => setPhase('choose')}>Choose another topic</Button><Button kind="secondary" onClick={back}>Back to modules</Button></div></section>;
  const prep = phase === 'prep'; return <section className="page stage sample-stage"><div className="stage-top"><div><span className="eyebrow"><Mic size={15}/> {prep ? 'PREPARATION TIME' : 'SPEAKING SAMPLE'}</span><h2>{prep ? 'Get ready!' : 'Speak now!'}</h2><p>{prep ? 'Think of ideas, examples, and useful vocabulary.' : 'Share your ideas clearly and in detail.'}</p></div><Timer remaining={left} total={prep ? 30 : 180} label={prep ? 'PREP' : 'LEFT'} danger={!prep}/></div><div className="prompt-box"><span>TOPIC</span><h3>{topic.title}</h3><p>{topic.prompt}</p></div><div className="actions">{prep ? <Button onClick={() => { setLeft(180); setPhase('speak'); }}>Skip prep <ArrowRight size={18}/></Button> : <><Button kind="secondary" onClick={() => setPaused(!paused)}>{paused ? <Play size={18}/> : <Pause size={18}/>} {paused ? 'Resume' : 'Pause'}</Button><Button kind="danger" onClick={() => setPhase('done')}>Finish early</Button></>}</div></section>;
}

function PracticeDashboard({ picture, sample, roleplay }: { picture: () => void; sample: () => void; roleplay: () => void }) {
  return <section className="page"><div className="hero"><div><span className="eyebrow"><Sparkles size={15}/> YOUR SPEAKING SPACE</span><h2>What would you like<br/>to practice today?</h2><p>Small speaking moments add up to big confidence.</p></div><Mascot /></div><div className="modules"><button className="module featured" onClick={picture}><i><Camera size={30}/></i><div><em>PICTURE PRACTICE</em><h3>Talk about the Picture</h3><p>Look closely, find the words, and speak freely.</p></div><ChevronRight /></button><button className="module sample-module" onClick={sample}><i><Mic size={29}/></i><div><em>NEW</em><h3>Speaking Sample</h3><p>Prepare for 30 seconds, then speak for 3 minutes.</p></div><ChevronRight /></button><button className="module roleplay-module" onClick={roleplay}><i><Users size={29}/></i><div><em>FUNGLISH</em><h3>Role Play</h3><p>Take a role, solve a challenge, and talk together.</p></div><ChevronRight /></button></div></section>;
}

function SetupList({ image, select, libraryImages, libraryLoaded, pickLibrary, start, back }: { image:string|null;select:(e:ChangeEvent<HTMLInputElement>)=>void;libraryImages:string[];libraryLoaded:boolean;pickLibrary:(src:string)=>void;start:()=>void;back:()=>void }) {
  const randomPick = () => { if (libraryImages.length) pickLibrary(libraryImages[Math.floor(Math.random() * libraryImages.length)]); };
  return <section className="page setup"><button className="back" onClick={back}><ArrowLeft size={17}/> ALL MODULES</button><div className="heading"><span className="eyebrow"><Camera size={15}/> TALK ABOUT THE PICTURE</span><h2>Choose a picture to describe</h2><p>Choose a saved picture or upload your own.</p></div><div className="list-picker-layout"><div className="library-pane"><div className="library-title"><div><span className="eyebrow"><ImageIcon size={15}/> YOUR PICTURE LIBRARY</span><h3>Choose a saved picture</h3></div><button className="random" onClick={randomPick} disabled={!libraryImages.length}><Shuffle size={16}/> Random photo</button></div><div className="library-list">{libraryImages.map(src => <button key={src} className={`list-photo ${image === src ? 'chosen' : ''}`} onClick={() => pickLibrary(src)}><img src={src} alt="Practice photo option"/><span>{decodeURIComponent(src.split('/').pop() ?? '').replace(/[-_]/g, ' ').replace(/\.[^/.]+$/, '')}</span>{image === src && <Check size={18}/>}</button>)}{libraryLoaded && !libraryImages.length && <div className="empty-library"><ImageIcon size={31}/><strong>Your library is ready</strong><p>Add image files to <code>public/practice-images</code> and they will appear here.</p></div>}{!libraryLoaded && <div className="empty-library">Loading your saved pictures…</div>}</div></div><div className="preview-pane"><label className="drop">{image ? <img src={image} alt="Selected picture preview"/> : <><i><ImagePlus size={36}/></i><h3>Upload a picture</h3><p>Choose one from your device</p><b><Upload size={17}/> Upload a photo</b></>}<input type="file" accept="image/*" onChange={select}/></label>{image && <div className="preview-start"><span><Check size={18}/> Picture ready!</span><Button onClick={start}>Start practice <ArrowRight size={19}/></Button></div>}</div></div></section>;
}

function Button({ children, onClick, kind = 'primary' }: { children: React.ReactNode; onClick?: () => void; kind?: 'primary' | 'secondary' | 'danger' }) {
  return <button onClick={onClick} className={`btn btn-${kind}`}>{children}</button>;
}
function Mascot({ small = false }: { small?: boolean }) { return <div className={`mascot ${small ? 'mascot-small' : ''}`}><span>🦉</span></div>; }
function Timer({ remaining, total, label, danger = false }: { remaining: number; total: number; label: string; danger?: boolean }) {
  const progress = Math.max(0, Math.min(100, ((total - remaining) / total) * 100)); const m = Math.floor(remaining / 60); const s = String(remaining % 60).padStart(2, '0');
  return <div className={`timer ${danger ? 'danger' : ''}`} style={{ background: `conic-gradient(${danger ? '#ff4b4b' : '#58cc02'} ${progress * 3.6}deg, #e7e7e7 0deg)` }}><div><strong>{m}:{s}</strong><span>{label}</span></div></div>;
}

export default function Home() {
  const [screen, setScreen] = useState<Screen>('dashboard'), [image, setImage] = useState<string | null>(null), [libraryImages, setLibraryImages] = useState<string[]>([]), [libraryLoaded, setLibraryLoaded] = useState(false), [prepLeft, setPrepLeft] = useState(PREP_SECONDS), [speakLeft, setSpeakLeft] = useState(SPEAK_SECONDS), [paused, setPaused] = useState(false), [audioUrl, setAudioUrl] = useState<string | null>(null), [elapsed, setElapsed] = useState(0);
  const recorder = useRef<MediaRecorder | null>(null), chunks = useRef<Blob[]>([]), stream = useRef<MediaStream | null>(null);
  useEffect(() => { if (screen !== 'prep') return; if (prepLeft <= 0) { startSpeaking(); return; } const id = setTimeout(() => setPrepLeft(x => x - 1), 1000); return () => clearTimeout(id); }, [screen, prepLeft]);
  useEffect(() => { if (screen !== 'speak' || paused) return; if (speakLeft <= 0) { finish(); return; } const id = setTimeout(() => { setSpeakLeft(x => x - 1); setElapsed(x => x + 1); }, 1000); return () => clearTimeout(id); }, [screen, speakLeft, paused]);
  useEffect(() => { fetch('/api/practice-images').then(response => response.json()).then(data => setLibraryImages(data.images ?? [])).catch(() => setLibraryImages([])).finally(() => setLibraryLoaded(true)); }, []);
  function fileSelected(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (image) URL.revokeObjectURL(image); setImage(URL.createObjectURL(file)); setPrepLeft(PREP_SECONDS); setSpeakLeft(SPEAK_SECONDS); setElapsed(0); setAudioUrl(null); setScreen('setup'); }
  function selectLibraryImage(src: string) { if (image?.startsWith('blob:')) URL.revokeObjectURL(image); setImage(src); setPrepLeft(PREP_SECONDS); setSpeakLeft(SPEAK_SECONDS); setElapsed(0); setAudioUrl(null); }
  async function startSpeaking() { setScreen('speak'); setPaused(false); try { const media = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.current = media; chunks.current = []; const r = new MediaRecorder(media); recorder.current = r; r.ondataavailable = e => { if (e.data.size) chunks.current.push(e.data); }; r.onstop = () => { if (chunks.current.length) setAudioUrl(URL.createObjectURL(new Blob(chunks.current, { type: 'audio/webm' }))); stream.current?.getTracks().forEach(t => t.stop()); }; r.start(); } catch {} }
  function finish() { if (recorder.current?.state && recorder.current.state !== 'inactive') recorder.current.stop(); setScreen('done'); }
  function reset() { recorder.current?.stop(); if (image) URL.revokeObjectURL(image); setImage(null); setAudioUrl(null); setScreen('setup'); }
  return <main><header className="topbar"><div className="brand"><Mascot small /><div><h1>Duolingi</h1><p>Build confidence, one conversation at a time.</p></div></div><nav><button className="active">Practice</button><button>Progress</button><button>Tips</button></nav><div className="streak">🔥 <b>7</b><small>day streak</small></div></header>
    {screen === 'dashboard' && <PracticeDashboard picture={() => setScreen('setup')} sample={() => setScreen('sample')} roleplay={() => setScreen('roleplay')} />}
    {screen === 'sample' && <SpeakingSample back={() => setScreen('dashboard')} />}
    {screen === 'roleplay' && <RolePlay back={() => setScreen('dashboard')} />}
    {screen === 'setup' && <SetupList image={image} select={fileSelected} libraryImages={libraryImages} libraryLoaded={libraryLoaded} pickLibrary={selectLibraryImage} start={() => image && setScreen('prep')} back={() => setScreen('dashboard')} />}
    {screen === 'prep' && image && <Stage image={image} prep left={prepLeft} skip={startSpeaking} back={() => setScreen('setup')} />}
    {screen === 'speak' && image && <Stage image={image} left={speakLeft} paused={paused} pause={() => { paused ? recorder.current?.resume() : recorder.current?.pause(); setPaused(!paused); }} finish={finish} restart={() => { recorder.current?.stop(); setSpeakLeft(SPEAK_SECONDS); setElapsed(0); startSpeaking(); }} />}
    {screen === 'done' && <Completion image={image} audio={audioUrl} elapsed={elapsed} again={reset} modules={() => setScreen('dashboard')} />}
  </main>;
}
function Dashboard({ go }: { go: () => void }) { const later = [['💬','Roleplay Conversation','Practice everyday dialogues'],['📖','Read Aloud','Sharpen your pronunciation'],['🌍','Topic Discussion','Share your point of view']]; return <section className="page"><div className="hero"><div><span className="eyebrow"><Sparkles size={15}/> YOUR SPEAKING SPACE</span><h2>What would you like<br/>to practice today?</h2><p>Small speaking moments add up to big confidence.</p></div><Mascot /></div><div className="modules"><button className="module featured" onClick={go}><i><Camera size={30}/></i><div><em>START HERE</em><h3>Talk about the Picture</h3><p>Look closely, find the words, and speak freely.</p></div><ChevronRight /></button>{later.map(([icon,title,text]) => <div className="module coming" key={title}><i>{icon}</i><div><em>COMING SOON</em><h3>{title}</h3><p>{text}</p></div><Clock3 /></div>)}</div></section>; }
function Setup({ image, select, libraryImages, libraryLoaded, pickLibrary, start, back }: { image:string|null;select:(e:ChangeEvent<HTMLInputElement>)=>void;libraryImages:string[];libraryLoaded:boolean;pickLibrary:(src:string)=>void;start:()=>void;back:()=>void }) {
  const randomPick = () => { if (libraryImages.length) pickLibrary(libraryImages[Math.floor(Math.random() * libraryImages.length)]); };
  return <section className="page setup"><button className="back" onClick={back}><ArrowLeft size={17}/> ALL MODULES</button><div className="heading"><span className="eyebrow"><Camera size={15}/> TALK ABOUT THE PICTURE</span><h2>Choose a picture to describe</h2><p>Upload your own or choose one from your practice-photo library.</p></div><div className="picker-layout"><div><div className="library-title"><div><span className="eyebrow"><ImageIcon size={15}/> YOUR PICTURE LIBRARY</span><h3>Choose a saved picture</h3></div><button className="random" onClick={randomPick} disabled={!libraryImages.length}><Shuffle size={16}/> Random photo</button></div><div className="library-grid">{libraryImages.map(src => <button key={src} className={`library-photo ${image === src ? 'chosen' : ''}`} onClick={() => pickLibrary(src)}><img src={src} alt="Practice photo option"/><span><Check size={16}/></span></button>)}{libraryLoaded && !libraryImages.length && <div className="empty-library"><ImageIcon size={31}/><strong>Your library is ready</strong><p>Add image files to <code>public/practice-images</code> and they will appear here.</p></div>}{!libraryLoaded && <div className="empty-library">Loading your saved pictures…</div>}</div></div><label className="drop">{image ? <img src={image} alt="Selected picture preview"/> : <><i><ImagePlus size={36}/></i><h3>Upload a picture</h3><p>Choose one from your device</p><b><Upload size={17}/> Upload a photo</b></>}<input type="file" accept="image/*" onChange={select}/></label></div>{image && <div className="start"><span><Check size={18}/> Picture ready!</span><Button onClick={start}>Start practice <ArrowRight size={19}/></Button></div>}</section>;
}
function Stage({ image, prep, left, paused, skip, back, pause, finish, restart }: { image:string;prep?:boolean;left:number;paused?:boolean;skip?:()=>void;back?:()=>void;pause?:()=>void;finish?:()=>void;restart?:()=>void }) { return <section className="page stage"><div className="stage-top"><div><span className="eyebrow"><Mic size={15}/> {prep ? 'PREPARATION TIME' : 'RECORDING'}</span><h2>{prep ? 'Get ready!' : 'Speak now!'}</h2><p>{prep ? 'Brainstorm key vocabulary and details.' : 'Describe the picture in detail.'}</p></div><Timer remaining={left} total={prep ? PREP_SECONDS : SPEAK_SECONDS} label={prep ? 'PREP' : 'LEFT'} danger={!prep}/></div><div className="picture"><img src={image} alt="Picture to describe"/>{!prep && <span className="record"><b/> RECORDING <strong>▂▅▇▃▆▂</strong></span>}</div>{prep ? <div className="actions"><Button kind="secondary" onClick={back}><ArrowLeft size={18}/> Change picture</Button><Button onClick={skip}>Skip prep <ArrowRight size={18}/></Button></div> : <div className="actions"><Button kind="secondary" onClick={pause}>{paused ? <Play size={18}/> : <Pause size={18}/>} {paused ? 'Resume' : 'Pause'}</Button><Button kind="danger" onClick={finish}><Check size={18}/> Finish early</Button><button className="restart" onClick={restart}><RotateCcw size={18}/> Restart</button></div>}</section>; }
function Completion({ image, audio, elapsed, again, modules }: { image:string|null;audio:string|null;elapsed:number;again:()=>void;modules:()=>void }) { const m=Math.floor(elapsed/60),s=String(elapsed%60).padStart(2,'0'); return <section className="page done"><div className="confetti">✦　✦　★　✦　✦</div><div className="trophy"><Trophy size={52}/></div><h2>Awesome speaking!</h2><p>You showed up and used your voice. That’s a win.</p><div className="review"><img src={image ?? ''} alt="Practice picture"/><div><em>YOUR PRACTICE</em><h3>{m}:{s} spoken</h3><p>{audio ? 'Listen back and notice one thing you did well.' : 'Recording unavailable — microphone permission may have been declined.'}</p>{audio && <audio controls src={audio}/>}</div><Volume2 /></div><div className="actions"><Button onClick={again}>Practice another picture <ArrowRight size={19}/></Button><Button kind="secondary" onClick={modules}>Back to modules</Button></div></section>; }
