'use client';

import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, Check, ChevronRight, Clock3, ImagePlus, Mic, Pause, Play, RotateCcw, Sparkles, Trophy, Upload, Volume2 } from 'lucide-react';

type Screen = 'dashboard' | 'setup' | 'prep' | 'speak' | 'done';
const PREP_SECONDS = 20;
const SPEAK_SECONDS = 90;

function Button({ children, onClick, kind = 'primary' }: { children: React.ReactNode; onClick?: () => void; kind?: 'primary' | 'secondary' | 'danger' }) {
  return <button onClick={onClick} className={`btn btn-${kind}`}>{children}</button>;
}
function Mascot({ small = false }: { small?: boolean }) { return <div className={`mascot ${small ? 'mascot-small' : ''}`}><span>🦉</span></div>; }
function Timer({ remaining, total, label, danger = false }: { remaining: number; total: number; label: string; danger?: boolean }) {
  const progress = Math.max(0, Math.min(100, ((total - remaining) / total) * 100)); const m = Math.floor(remaining / 60); const s = String(remaining % 60).padStart(2, '0');
  return <div className={`timer ${danger ? 'danger' : ''}`} style={{ background: `conic-gradient(${danger ? '#ff4b4b' : '#58cc02'} ${progress * 3.6}deg, #e7e7e7 0deg)` }}><div><strong>{m}:{s}</strong><span>{label}</span></div></div>;
}

export default function Home() {
  const [screen, setScreen] = useState<Screen>('dashboard'), [image, setImage] = useState<string | null>(null), [prepLeft, setPrepLeft] = useState(PREP_SECONDS), [speakLeft, setSpeakLeft] = useState(SPEAK_SECONDS), [paused, setPaused] = useState(false), [audioUrl, setAudioUrl] = useState<string | null>(null), [elapsed, setElapsed] = useState(0);
  const recorder = useRef<MediaRecorder | null>(null), chunks = useRef<Blob[]>([]), stream = useRef<MediaStream | null>(null);
  useEffect(() => { if (screen !== 'prep') return; if (prepLeft <= 0) { startSpeaking(); return; } const id = setTimeout(() => setPrepLeft(x => x - 1), 1000); return () => clearTimeout(id); }, [screen, prepLeft]);
  useEffect(() => { if (screen !== 'speak' || paused) return; if (speakLeft <= 0) { finish(); return; } const id = setTimeout(() => { setSpeakLeft(x => x - 1); setElapsed(x => x + 1); }, 1000); return () => clearTimeout(id); }, [screen, speakLeft, paused]);
  function fileSelected(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (image) URL.revokeObjectURL(image); setImage(URL.createObjectURL(file)); setPrepLeft(PREP_SECONDS); setSpeakLeft(SPEAK_SECONDS); setElapsed(0); setAudioUrl(null); setScreen('setup'); }
  async function startSpeaking() { setScreen('speak'); setPaused(false); try { const media = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.current = media; chunks.current = []; const r = new MediaRecorder(media); recorder.current = r; r.ondataavailable = e => { if (e.data.size) chunks.current.push(e.data); }; r.onstop = () => { if (chunks.current.length) setAudioUrl(URL.createObjectURL(new Blob(chunks.current, { type: 'audio/webm' }))); stream.current?.getTracks().forEach(t => t.stop()); }; r.start(); } catch {} }
  function finish() { if (recorder.current?.state && recorder.current.state !== 'inactive') recorder.current.stop(); setScreen('done'); }
  function reset() { recorder.current?.stop(); if (image) URL.revokeObjectURL(image); setImage(null); setAudioUrl(null); setScreen('setup'); }
  return <main><header className="topbar"><div className="brand"><Mascot small /><div><h1>English Speaking Partner</h1><p>Build confidence, one conversation at a time.</p></div></div><nav><button className="active">Practice</button><button>Progress</button><button>Tips</button></nav><div className="streak">🔥 <b>7</b><small>day streak</small></div></header>
    {screen === 'dashboard' && <Dashboard go={() => setScreen('setup')} />}
    {screen === 'setup' && <Setup image={image} select={fileSelected} start={() => image && setScreen('prep')} back={() => setScreen('dashboard')} />}
    {screen === 'prep' && image && <Stage image={image} prep left={prepLeft} skip={startSpeaking} back={() => setScreen('setup')} />}
    {screen === 'speak' && image && <Stage image={image} left={speakLeft} paused={paused} pause={() => { paused ? recorder.current?.resume() : recorder.current?.pause(); setPaused(!paused); }} finish={finish} restart={() => { recorder.current?.stop(); setSpeakLeft(SPEAK_SECONDS); setElapsed(0); startSpeaking(); }} />}
    {screen === 'done' && <Completion image={image} audio={audioUrl} elapsed={elapsed} again={reset} modules={() => setScreen('dashboard')} />}
  </main>;
}
function Dashboard({ go }: { go: () => void }) { const later = [['💬','Roleplay Conversation','Practice everyday dialogues'],['📖','Read Aloud','Sharpen your pronunciation'],['🌍','Topic Discussion','Share your point of view']]; return <section className="page"><div className="hero"><div><span className="eyebrow"><Sparkles size={15}/> YOUR SPEAKING SPACE</span><h2>What would you like<br/>to practice today?</h2><p>Small speaking moments add up to big confidence.</p></div><Mascot /></div><div className="modules"><button className="module featured" onClick={go}><i><Camera size={30}/></i><div><em>START HERE</em><h3>Talk about the Picture</h3><p>Look closely, find the words, and speak freely.</p></div><ChevronRight /></button>{later.map(([icon,title,text]) => <div className="module coming" key={title}><i>{icon}</i><div><em>COMING SOON</em><h3>{title}</h3><p>{text}</p></div><Clock3 /></div>)}</div></section>; }
function Setup({ image, select, start, back }: { image:string|null;select:(e:ChangeEvent<HTMLInputElement>)=>void;start:()=>void;back:()=>void }) { return <section className="page setup"><button className="back" onClick={back}><ArrowLeft size={17}/> ALL MODULES</button><div className="heading"><span className="eyebrow"><Camera size={15}/> TALK ABOUT THE PICTURE</span><h2>Choose a picture to describe</h2><p>Pick anything that gives you something interesting to say.</p></div><div className="upload-grid"><label className="drop">{image ? <img src={image} alt="Selected picture"/> : <><i><ImagePlus size={36}/></i><h3>Drop an image here</h3><p>or choose one from your device</p><b><Upload size={17}/> Upload a photo</b></>}<input type="file" accept="image/*" onChange={select}/></label><aside><span>💡</span><div><h3>A little tip</h3><p>Choose a photo with people, places, or details. They make it easier to keep talking!</p></div></aside></div>{image && <div className="start"><span><Check size={18}/> Picture ready!</span><Button onClick={start}>Start practice <ArrowRight size={19}/></Button></div>}</section>; }
function Stage({ image, prep, left, paused, skip, back, pause, finish, restart }: { image:string;prep?:boolean;left:number;paused?:boolean;skip?:()=>void;back?:()=>void;pause?:()=>void;finish?:()=>void;restart?:()=>void }) { return <section className="page stage"><div className="stage-top"><div><span className="eyebrow"><Mic size={15}/> {prep ? 'PREPARATION TIME' : 'RECORDING'}</span><h2>{prep ? 'Get ready!' : 'Speak now!'}</h2><p>{prep ? 'Brainstorm key vocabulary and details.' : 'Describe the picture in detail.'}</p></div><Timer remaining={left} total={prep ? PREP_SECONDS : SPEAK_SECONDS} label={prep ? 'PREP' : 'LEFT'} danger={!prep}/></div><div className="picture"><img src={image} alt="Picture to describe"/>{!prep && <span className="record"><b/> RECORDING <strong>▂▅▇▃▆▂</strong></span>}</div>{prep ? <div className="actions"><Button kind="secondary" onClick={back}><ArrowLeft size={18}/> Change picture</Button><Button onClick={skip}>Skip prep <ArrowRight size={18}/></Button></div> : <div className="actions"><Button kind="secondary" onClick={pause}>{paused ? <Play size={18}/> : <Pause size={18}/>} {paused ? 'Resume' : 'Pause'}</Button><Button kind="danger" onClick={finish}><Check size={18}/> Finish early</Button><button className="restart" onClick={restart}><RotateCcw size={18}/> Restart</button></div>}</section>; }
function Completion({ image, audio, elapsed, again, modules }: { image:string|null;audio:string|null;elapsed:number;again:()=>void;modules:()=>void }) { const m=Math.floor(elapsed/60),s=String(elapsed%60).padStart(2,'0'); return <section className="page done"><div className="confetti">✦　✦　★　✦　✦</div><div className="trophy"><Trophy size={52}/></div><h2>Awesome speaking!</h2><p>You showed up and used your voice. That’s a win.</p><div className="review"><img src={image ?? ''} alt="Practice picture"/><div><em>YOUR PRACTICE</em><h3>{m}:{s} spoken</h3><p>{audio ? 'Listen back and notice one thing you did well.' : 'Recording unavailable — microphone permission may have been declined.'}</p>{audio && <audio controls src={audio}/>}</div><Volume2 /></div><div className="actions"><Button onClick={again}>Practice another picture <ArrowRight size={19}/></Button><Button kind="secondary" onClick={modules}>Back to modules</Button></div></section>; }
